"""add_cart_item

Revision ID: 49de79930699
Revises: 4d5944be2833
Create Date: 2025-08-15 17:27:06.500907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49de79930699'
down_revision: Union[str, Sequence[str], None] = '4d5944be2833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_item_cart_id_fkey'), 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key(op.f('cart_item_cart_id_fkey'), 'cart_item', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
